title: Well&Content
email: glitchedinorbit@gmail.com
description: Resources, tools, and support for neurodivergent creators
keywords:
  - "wellcontent"
  - "well content"
  - "well-content"
  - "glitchedinorbit"
  - "content creation"
  - "creator wellbeing"
  - "content creator tools"
  - "streaming"
  - "streaming tips"
  - "content creator mental health"
  - "streamer resources"
  - "streamer tools"
  - "streamer guides"
  - "streamer burnout prevention"
  - "healthy streaming habits"
  - "self-care for streamers"
  - "stress management for streamers"
  - "mindfulness for content creators"
  - "time management for streamers"
  - "work-life balance for content creators"
  - "mental health for creators"
  - "productivity for content creators"
  - "streamer mental health"
  - "streamer productivity"
author: Chloe
baseurl: ""
url: "https://wellcontent.io"
permalink: /:slug
collections:
  posts:
    output: true
  templates:
    output: true
  guides:
    output: true
breadcrumbs:
  home: "/"
  templates: "/templates"
  guides: "/guides"
  posts: "/blog"
  about: "/about"

# Social Profiles
twitter_username: glitchedinorbit
github_username:
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: G-FP7E82B5MW # Enter your Google tag

# Build settings
markdown: kramdown
syntax_highlighter: rouge
kramdown:
  input: GFM
  enable_coderay: false
  toc_levels: 1..3
  math: true
  fence_classes: true

paginate: 5
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - amp-jekyll

# Utterances / Comment Section
utterances:
  repo: "wellcontent.github.io"
  issue-term: "pathname"
  label: "utteranc.es"
  theme: "github-dark"
