title:              Well&Content
email:              glitchedinorbit@gmail.com
description:        Wellbeing guides for streamers and content creators
author:             Well&Content
baseurl:            ""
url:                "https://wellcontent.io"
permalink:          /:slug/
collections:
  resources:
    output: true
  guides:
    output: true

# Social Profiles
twitter_username:   glitchedinorbit
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-FP7E82B5MW # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - amp-jekyll

utterances:
  repo: "wellcontent.github.io"
  issue-term: "pathname"
  label: "utteranc.es"
  theme: "github-dark"